In [1]:
import numpy as np

arr = np.linspace(0, 20, 5)
arr

array([ 0.,  5., 10., 15., 20.])

In [2]:
arr2 = np.zeros(5)
arr2

array([0., 0., 0., 0., 0.])

In [3]:
arr3 = np.ones((3, 3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
arr4 = np.random.rand(4, 4)
arr4

array([[0.98707266, 0.37390529, 0.81394052, 0.38149477],
       [0.37185993, 0.23793556, 0.57290382, 0.09476034],
       [0.89943916, 0.01197977, 0.90632187, 0.64677617],
       [0.56932063, 0.20496806, 0.88595775, 0.00215677]])

In [7]:
arr5 = np.array([1, 2, 3, 4, 5])
arr5

print("First element:", arr5[0])
print("Second element:", arr5[1])

First element: 1
Second element: 2


In [9]:
sub_arr1 = arr5[0:3]
print("Sub-array:", sub_arr1)

range_val = max(sub_arr1) - min(sub_arr1)
print("Range of elements from 1st to 3rd:", range_val)

Sub-array: [1 2 3]
Range of elements from 1st to 3rd: 2


In [10]:
sub_arr2 = arr5[1:]
print("Sub array: ", sub_arr2)

range_val2 = max(sub_arr2) - min(sub_arr2)
print("Range of elements from 2nd element:", range_val2)

Sub array:  [2 3 4 5]
Range of elements from 2nd element: 3


In [13]:
sub_arr3 = arr5[-2:]
print("Sub array: ", sub_arr3)

range_val3 = max(sub_arr3) - min(sub_arr1)
print("Range of elements from index - 2:", range_val3)

Sub array:  [4 5]
Range of elements from index - 2: 4


In [14]:
import numpy as np

arr1 = [1,2,3]
arr2 = [4,5,6]

arr_2D = np.array([arr1, arr2])
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
print("1st row 2nd col element:", arr_2D[0,1])
print("2nd row elements:", arr_2D[1])
print("3rd column elements:", arr_2D[:,2])

range_row1 = max(arr_2D[0]) - min(arr_2D[0])
print("Range of elements in 1st row:", range_row1)

1st row 2nd col element: 2
2nd row elements: [4 5 6]
3rd column elements: [3 6]
Range of elements in 1st row: 2


In [16]:
sub_arr = arr_2D[0:2, 1:3]
print("Sub array:\n", sub_arr)

range_val = np.max(sub_arr) - np.min(sub_arr)
print("Range of element in 1st and 2nd row with 2nd and 3rd col:",range_val)

Sub array:
 [[2 3]
 [5 6]]
Range of element in 1st and 2nd row with 2nd and 3rd col: 4
