In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [2]:
list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

np_arr = np.array(list)
print(np_arr)

[1 2 3 4 5 6 7 8 9]


In [3]:
import numpy as np

rows = 3
cols = 3

arr = [[j for j in range(cols)] for i in range(rows)]
arr

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]

In [4]:
import numpy as np

x = 3
y = 3
z = 3

arr = [[[j for j in range(x)] for i in range(y)] for z in range(z)]
arr

[[[0, 1, 2], [0, 1, 2], [0, 1, 2]],
 [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
 [[0, 1, 2], [0, 1, 2], [0, 1, 2]]]

In [5]:
import numpy as np

array_1 = [1, 2, 3, 4]
array_2 = [5, 6, 7, 8]
array_3 = [3, 4, 5, 6]

arr_3d = np.array([array_1, array_2, array_3])
print(arr_3d)

[[1 2 3 4]
 [5 6 7 8]
 [3 4 5 6]]


In [6]:
import numpy as np

arr1 = [1, 2, 3, 4, 5]
arr2 = [2, 3, 4, 5, 6]
arr3 = [3, 4, 5, 6, 7]
arr4 = [5, 6, 7, 8, 9]

arr_4d = np.array([arr1, arr2, arr3, arr4])
print(arr_4d)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [5 6 7 8 9]]
